### ISSUE TITLE
Install tldjs under root

### ISSUE THREAD

**Issue by cveld** [oncletom/tld.js#143]
When I try `npm i tldjs` running under root I get the following error:

```
root@mymachine:~/test# npm i tldjs

> tldjs@2.3.1 postinstall /root/test/node_modules/tldjs
> node ./bin/postinstall.js

internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '/root/test/node_modules/tldjs/bin/postinstall.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tldjs@2.3.1 postinstall: `node ./bin/postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tldjs@2.3.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-11-26T14_09_29_771Z-debug.log
```

What must I do to successfully install tldjs under root?

**Comment by oncletom** [comment]
Why do you need to install it as root? Does it work when you install it as non-root user?
